### ISSUE TITLE
Hello from Algolia 👋

### ISSUE THREAD

**Issue by redox** [techouse/alfred-django-docs#1]
Hello,

really cool to see this Alfred workflow, awesome initiative :)

I was reading your README and stumbled upon

> Built using Alfred-Workflow. The search is powered by Algolia search using a free Community plan. Since the community plan only supports 10,000 records I had to cut it short and support only 2 branches of the documentation. That is the reason why there is no documentation for the 2.0 branch.

Which of course made me sad :) So I've just upgraded your FREE plan to 50k records and 500k operations. Enjoy ;)

**Comment by techouse** [comment]
Hey!

Wow! Didn't expect that :D Thanx a lot! I'll get on building an index for all the currently supported Django docs now :) HUGE THANX!

Using Algolia for these types of intensive search apps that need to be lightning fast seemed the natural choice.

Again THANK YOU VERY MUCH 🍺 😇

**Comment by redox** [comment]
Very welcome :)
